# Generated by Django 4.2.23 on 2025-07-15 13:45

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(blank=True, max_length=50, verbose_name='暱稱')),
                ('login_type', models.CharField(choices=[('normal', '一般'), ('google', 'Google'), ('guest', '訪客')], default='normal', max_length=10, verbose_name='登入方式')),
                ('is_guest', models.BooleanField(default=False, verbose_name='是否為訪客')),
                ('user_avatar', models.CharField(default='img/avatars/default.png', max_length=255, verbose_name='頭像路徑')),
                ('diamonds', models.IntegerField(default=1, verbose_name='鑽石數量')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email address')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('chapter_id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter_number', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('background_image', models.CharField(max_length=255)),
                ('bg_music', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('character_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('character_avatar', models.CharField(max_length=255, verbose_name='角色頭像')),
                ('character_sprite', models.CharField(blank=True, max_length=255, verbose_name='角色立繪圖')),
                ('intro', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GameType',
            fields=[
                ('game_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='遊戲名稱')),
                ('background_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='遊戲背景圖')),
                ('description', models.TextField(blank=True, verbose_name='遊戲描述')),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('planet_id', models.AutoField(primary_key=True, serialize=False)),
                ('planet_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuizRecord',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False)),
                ('correct_count', models.IntegerField()),
                ('stars_earned', models.IntegerField()),
                ('life_crystal_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthTrack',
            fields=[
                ('quiz_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='test0621.quizrecord', verbose_name='觸發的測驗記錄')),
                ('achievement', models.TextField(blank=True, verbose_name='成就描述')),
                ('is_cracked', models.BooleanField(default=False, verbose_name='獎勵是否已領取')),
            ],
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('music_volume', models.IntegerField(default=50)),
                ('voice_toggle', models.BooleanField(default=True)),
                ('font', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StarUnlockLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='解鎖時間')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.chapter', verbose_name='解鎖的章節')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '關卡解鎖日誌',
                'verbose_name_plural': '關卡解鎖日誌',
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('easy', '簡單'), ('medium', '中等'), ('hard', '困難')], max_length=10)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_answer', models.CharField(max_length=10)),
                ('enemy_image', models.CharField(blank=True, max_length=255, null=True)),
                ('player_image', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='test0621.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='FullStory',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('introduction', models.TextField(blank=True, default='')),
                ('full_text', models.TextField()),
                ('is_unlocked', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.chapter')),
                ('characters', models.ManyToManyField(to='test0621.character', verbose_name='登場角色')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.planet')),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('dialogue_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('text', models.TextField()),
                ('voice_file', models.CharField(blank=True, max_length=255, null=True)),
                ('background_image', models.CharField(blank=True, max_length=255, null=True)),
                ('bg_music', models.CharField(blank=True, max_length=255, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.chapter')),
                ('character_on_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues_on_left', to='test0621.character', verbose_name='左側角色')),
                ('character_on_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dialogues_on_right', to='test0621.character', verbose_name='右側角色')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialogues_spoken', to='test0621.character', verbose_name='發言者')),
            ],
        ),
        migrations.CreateModel(
            name='DailyCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField(auto_now_add=True, unique=True, verbose_name='打卡日期')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '每日打卡記錄',
                'verbose_name_plural': '每日打卡記錄',
                'ordering': ['-check_in_date'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test0621.gametype', verbose_name='使用的遊戲類型'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='planet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.planet'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('locked', '未解鎖'), ('unlocked', '已解鎖'), ('in_progress', '進行中'), ('completed', '已完成')], max_length=20)),
                ('last_played', models.DateTimeField(default=django.utils.timezone.now)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.chapter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'chapter')},
            },
        ),
        migrations.CreateModel(
            name='UnlockedAvatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar_path', models.CharField(max_length=255, verbose_name='頭像路徑')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, verbose_name='解鎖時間')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '玩家解鎖頭像',
                'verbose_name_plural': '玩家解鎖頭像',
                'unique_together': {('user', 'avatar_path')},
            },
        ),
        migrations.CreateModel(
            name='ChapterCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.chapter')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test0621.character')),
            ],
            options={
                'unique_together': {('chapter', 'character')},
            },
        ),
    ]
