# Generated by Django 4.2.23 on 2025-07-14 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test0621', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='game_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='test0621.gametype', verbose_name='使用的遊戲類型'),
        ),
        migrations.AlterField(
            model_name='gametype',
            name='background_image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='遊戲背景圖'),
        ),
    ]
